config/routes.rb
GoletaValleyBeautifulPostgres::Application.routes.draw do

  get '/', :to => 'trees#index'

  resources :tree_types, :only => [:index, :show]

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :trees, :only => [:index, :create]
  resources :groups, :agencies , :shallow => true do |group|
    resources :trees
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :description, :name

  #Relationships
  has_and_belongs_to_many :trees

  #custom JSON
  acts_as_api
  api_accessible :public do |template|
    template.add :description
    template.add :name
  end

  def tree_count
    self.trees.count
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
end

app/views/groups/_form.html.haml
= form_for @group do |f|
  - if @group.errors.any?
    #error_explanation
      %h2= "#{pluralize(@group.errors.count, "error")} prohibited this group from being saved:"
      %ul
        - @group.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .actions
    = f.submit 'Save'

app/views/groups/edit.html.haml
%h1 Editing group

= render 'form'

= link_to 'Show', @group
\|
= link_to 'Back', groups_path

app/views/groups/index.html.haml
%h1 Listing groups

%table
  %tr
    %th Name--------
    %th Description-------
    %th # trees
    %th
    %th

  - @groups.each do |group|
    %tr
      %td= group.name
      %td= group.description
      %td= group.trees.count
      %td= link_to 'Show', group
      %td= link_to 'Edit', edit_group_path(group)
      %td= link_to 'Destroy', group, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Group', new_group_path

app/views/groups/new.html.haml
%h1 New group

= render 'form'

= link_to 'Back', groups_path

app/views/groups/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @group.name
%p
  %b Description:
  = @group.description

= link_to 'Edit', edit_group_path(@group)
\|
= link_to 'Back', groups_path