config/routes.rb
GoletaValleyBeautifulPostgres::Application.routes.draw do

  get '/', :to => 'trees#index'

  resources :tree_types, :only => [:index, :show]

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :trees, :only => [:index, :create]
  resources :groups, :agencies , :shallow => true do |group|
    resources :trees
  end

end

app/models/tree.rb
class Tree < ActiveRecord::Base
  attr_accessible :tree_type_id,
                  :id,
                  :diameter_at_height,
                  :height,
                  :spread,
                  :grove,

                  #Dates
                  :maint_date,
                  :plant_date,
                  :replace_date,

                  :group_ids,
                  :agency_id,
                  :tree_status_id,

                  #LEGACY FIELDS
                  :street_no,
                  :street,

                  #SPATIAL FIELDS
                  :lonlat,
                  :longitude,
                  :latitude

  #Relationships
  belongs_to :agency
  belongs_to :tree_type
  has_one :tree_status
  has_one :tree_genus, :through => :tree_type
  has_and_belongs_to_many :groups
  accepts_nested_attributes_for :tree_type


  #Geospatial
  acts_as_gmappable :lat => "latitude", :lng => "longitude", :process_geocoding => :geocode?
  self.rgeo_factory_generator = RGeo::Geos.factory_generator(:srid => 4326)
  set_rgeo_factory_for_column(:lonlat, RGeo::Geographic.spherical_factory(:srid => 4326))

    #address -> coords
  geocoded_by :address
  after_initialize :init
    #coords -> address
  reverse_geocoded_by :latitude, :longitude

   #custom JSON
  acts_as_api
  api_accessible :public do |template|
    template.add :tree_type_id
    template.add :agency_id
    template.add :status
    template.add :diameter_at_height
    template.add :height
    template.add :spread
    template.add :longitude
    template.add :latitude
  end





  def self.last_updated
    Tree.order( "updated_at DESC").limit(1)
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |tree|
        csv << tree.attributes.values_at(*column_names)
      end
    end
  end

  def self.search(search)
    if search
      where('common_name LIKE ?', "%#{search}%")
    else
      scoped
    end
  end

  def to_s
    "#{tree_type.common_name} (#{tree_type.genus} #{tree_type.species})"
  end

  def common_name
    "#{tree_type.common_name}"
  end

  def scientific_name
    "#{tree_type.genus} #{tree_type.species}"
  end

  def genus
    "#{tree_type.genus}"
  end

  def species
    "#{tree_type.species}"
  end

  def address
    "#{street_no.to_s} #{[street, "CA", "USA"].compact.join(', ')}"
  end

  def init
    self.lonlat ||= Tree.rgeo_factory_for_column(:lonlat).point(0, 0)
  end

#def latitude
#  self.lonlat.lat
#end
  #
  #def latitude=(value)
  #  self.latitude = value
  #  lon = self.lonlat.lon
  #  self.lonlat = Tree.rgeo_factory_for_column(:lonlat).point(lon, value)
  #end
  ##
  ##def longitude
  ##  self.lonlat.lon
  ##end
  ##
  #def longitude=(value)
  #  self.longitude = value
  #  lat = self.lonlat.lat
  #  self.lonlat = Tree.rgeo_factory_for_column(:lonlat).point(longitude, lat)
  #end

  def synclatlon()
    val1 = self.latitude
    val2 = self.longitude
    self.lonlat = Tree.rgeo_factory_for_column(:lonlat).point(val2, val1)
  end


end

app/models/tree_type.rb
class TreeType < ActiveRecord::Base
  attr_accessible :common_name, :tree_genus_id, :species

  belongs_to :tree_genus, :dependent =>:destroy
  has_many :trees
  accepts_nested_attributes_for :tree_genus

  acts_as_api
  api_accessible :public do |template|
    template.add :id
    template.add :common_name
    template.add :genus
    template.add :species
  end

  def to_s
    "#{common_name}"
  end

  def genus
    tree_genus.genus
  end

end

app/controllers/trees_controller.rb
class TreesController < ApplicationController
  # GET /trees
  # GET /trees.json
  helper_method :sort_column, :sort_direction
  skip_before_filter :verify_authenticity_token, :if => Proc.new { |c| c.request.format == 'application/json' }
  def index
    if params[:agency_id]
      @q = Tree.where(agency_id: params[:agency_id])
      @agency = Agency.find(params[:agency_id])
      @trees = @q.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])
      @json = @q.to_gmaps4rails do |tree, marker|
        marker.infowindow render_to_string(:partial => "trees/show", :locals => { :tree => tree })
        marker.title "#{tree}"
      end
    else
      @trees = Tree.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])
      @json = Tree.all(limit: 2000).to_gmaps4rails do |tree, marker|
        marker.infowindow render_to_string(:partial => "trees/show", :locals => { :tree => tree })
        marker.title "#{tree}"
      end
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render_for_api :public, :json => @trees, :root => :trees }
      format.csv { send_data @trees.to_csv }
    end
  end

  # GET /trees/1
  # GET /trees/1.json
  def show
    @tree = Tree.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tree }

  end

  end

  # GET /trees/new
  # GET /trees/new.json
  def new
    @tree = Tree.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tree }
    end
  end

  # GET /trees/1/edit
  def edit
    @tree = Tree.find(params[:id])
  end

  # POST /trees
  # POST /trees.json
  def create
    @tree = Tree.new(params[:tree])
    @tree.synclatlon
    respond_to do |format|
      if @tree.save
        format.html { redirect_to @tree, notice: 'Tree was successfully created.' }
        format.json { render json: @tree, status: :created, location: @tree }
      else
        format.html { render 'new' }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trees/1
  # PUT /trees/1.json
  def update
    @tree = Tree.find(params[:id])

    respond_to do |format|
      if @tree.update_attributes(params[:tree])
        format.html { redirect_to @tree, notice: 'Tree was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render "edit" }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trees/1
  # DELETE /trees/1.json
  def destroy
    @tree = Tree.find(params[:id])
    @tree.destroy

    respond_to do |format|
      format.html { redirect_to trees_url }
      format.json { head :no_content }
    end
  end

  def sort_column
    Tree.column_names.include?(params[:sort]) ? params[:sort] : "height"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/trees_helper.rb
module TreesHelper
end

app/views/trees/_form.html.haml
= form_for @tree do |f|
  - if @tree.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tree.errors.count, "error")} prohibited this tree from being saved:"
      %ul
        - @tree.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/trees/_map.html.haml
- if @trees
  %h3 Tree Map
  #map
    = gmaps(:markers => {:data => @json },        |
            :map_options => { :auto_zoom => true, :zoom => 10,   |
            :center_on_user => false })                           |

- if @tree
  %h3 Tree Map

  #map
  = gmaps(:markers => {:data => @json },        |
          :map_options => { :auto_zoom => true, :zoom => 10,   |
          :center_on_user => false }) |

app/views/trees/_show.html.haml
%h3
  = tree.common_name
= tree.scientific_name
.stats
  %b Agency:
  - if tree.agency
    = tree.agency
  - else
    nil
  %br
  %b DBH:
  - if tree.diameter_at_height
    = tree.diameter_at_height
  - else
    %i nil
  %br
  %b Height:
  - if tree.height
    = tree.height
  - else
    %i nil
  %br
  %b Spread:
  - if tree.spread
    = tree.spread
  - else
    %i nil

app/views/trees/edit.html.haml
%h1 Editing tree

= render 'form'

= link_to 'Show', @tree
\|
= link_to 'Back', trees_path

app/views/trees/index.html.haml
%h3 Listing trees

%div{:class => "well pull-left", :id => "treeList"}

  = render 'agencies/list'
  %div{:data => {"pjax-container" => true}}

    %div{:class => "trees pull-left"}
      %table{:class => "table"}
        %tr
          %th Common Name
          %th Genus
          %th Species
          %th DBH
          %th Height
          %th Agency
          - @trees.each do |tree|
            %tr
              %td
                = link_to tree.tree_type.common_name, tree_path(tree)
              %td= tree.genus
              %td= tree.species
              %td= tree.diameter_at_height
              %td= tree.height
              %td
                - if tree.agency
                  = tree.agency.shortname
                - else

    = will_paginate @trees

app/views/trees/new.html.haml
%h1 New tree

= render 'form'

= link_to 'Back', trees_path

app/views/trees/show.html.haml
%p#notice= notice
= link_to 'Edit', edit_tree_path(@tree)
\|
= link_to 'Back', agency_trees_path(@tree.agency)