config/routes.rb
GoletaValleyBeautifulPostgres::Application.routes.draw do

  get '/', :to => 'trees#index'

  resources :tree_types, :only => [:index, :show]

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :trees, :only => [:index, :create]
  resources :groups, :agencies , :shallow => true do |group|
    resources :trees
  end

end

app/models/agency.rb
class Agency < ActiveRecord::Base
  attr_accessible :description, :name, :shortname

  #Relationships
  has_many :trees

  #Pretty URLs

  #custom JSON
  acts_as_api
  api_accessible :public do |template|
    template.add :id
    template.add :name
    template.add :shortname
  end

  def to_s
    "#{shortname} - #{name}"
  end

  def list_s
    "#{shortname} - #{name} : #{trees.count}"
  end

end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
  # GET /agencies
  # GET /agencies.json
  def index
    @agencies = Agency.all

    respond_to do |format|
      format.html # index.html.haml
      format.json { render_for_api :public, :json => @agencies, :root => :agencies }
    end
  end

  # GET /agencies/1
  # GET /agencies/1.json
  def show
    @agency = Agency.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @agency }
    end
  end

  # GET /agencies/new
  # GET /agencies/new.json
  def new
    @agency = Agency.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @agency }
    end
  end

  # GET /agencies/1/edit
  def edit
    @agency = Agency.find(params[:id])
  end

  # POST /agencies
  # POST /agencies.json
  def create
    @agency = Agency.new(params[:agency])

    respond_to do |format|
      if @agency.save
        format.html { redirect_to @agency, notice: 'Agency was successfully created.' }
        format.json { render json: @agency, status: :created, location: @agency }
      else
        format.html { render "new" }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /agencies/1
  # PUT /agencies/1.json
  def update
    @agency = Agency.find(params[:id])

    respond_to do |format|
      if @agency.update_attributes(params[:agency])
        format.html { redirect_to @agency, notice: 'Agency was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render "edit" }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agencies/1
  # DELETE /agencies/1.json
  def destroy
    @agency = Agency.find(params[:id])
    @agency.destroy

    respond_to do |format|
      format.html { redirect_to agencies_url }
      format.json { head :no_content }
    end
  end
end

app/views/agencies/_form.html.haml
= form_for @agency do |f|
  - if @agency.errors.any?
    #error_explanation
      %h2= "#{pluralize(@agency.errors.count, "error")} prohibited this agency from being saved:"
      %ul
        - @agency.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :shortname
    = f.text_field :shortname
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .actions
    = f.submit 'Save'

app/views/agencies/_list.html.haml
.agency_list
  .btn-group
    %a{ class: "btn dropdown-toggle btn-block", data: {"toggle" => "dropdown"}, href: '#'}
      %span{ :class => "caret" }
      %i
        = @agency if @agency
        = "All Trees" unless @agency
    %ul{ :class => "dropdown-menu" }
      %li
        = link_to "All Trees", trees_path
      - Agency.all.each do |a|
        - if a.trees.count != 0
          %li
            = link_to a.list_s, agency_trees_path(a)

app/views/agencies/edit.html.haml
%h1 Editing agency

= render 'form'

= link_to 'Show', @agency
\|
= link_to 'Back', agencies_path

app/views/agencies/index.html.haml
%h1 Listing agencies

%table
  %tr
    %th Identity
    %th Name
    %th Description
    %th # Trees
    %th
    %th

  - @agencies.each do |agency|
    %tr
      %td= agency.shortname
      %td= agency.name
      %td= agency.description
      %td= agency.trees.count
      %td= link_to 'Show', agency
      %td= link_to 'Edit', edit_agency_path(agency)
      %td= link_to 'Destroy', agency, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Agency', new_agency_path

app/views/agencies/new.html.haml
%h1 New agency

= render 'form'

= link_to 'Back', agencies_path

app/views/agencies/show.html.haml
%p#notice= notice

%p
  %b Shortname:
  = @agency.shortname
%p
  %b Name:
  = @agency.name
%p
  %b Description:
  = @agency.description

= link_to 'Edit', edit_agency_path(@agency)
\|
= link_to 'Back', agencies_path